name: Build on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Install pyinstaller
        run:  pip install pyinstaller 

      - name: Run build script
        run: python scripts/build.py

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build_win_main
          path: build_win/main
