name: Build and Package All OS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .exe
        run: python scripts/build.py --target exe

      - name: Upload .exe
        uses: actions/upload-artifact@v4
        with:
          name: app-windows-exe
          path: build_win/main

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y python3-pip ruby ruby-dev rpm rpm-build snapcraft
          sudo gem install --no-document fpm

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .deb
        run: python scripts/build.py --target deb

      - name: Build .rpm
        run: python scripts/build.py --target rpm

      - name: Build .snap
        run: python scripts/build.py --target snap

      - name: Upload Linux packages
        uses: actions/upload-artifact@v4
        with:
          name: app-linux-packages
          path: |
            *.deb
            *.rpm
            *.snap

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dmg tool
        run: |
          brew install node
          npm install -g create-dmg

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build .dmg
        run: python scripts/build.py --target dmg

      - name: Upload .dmg
        uses: actions/upload-artifact@v4
        with:
          name: app-macos-dmg
          path: build_win/main
